import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

import NavbarComponent from '../components/navigation/NavbarComponent';
import DaySheetComponent from '../components/DaySheetComponents/DaySheetComponent';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <NavbarComponent />
          <main className={styles.main}>

            <h1 className="text-3xl font-bold underline">
              Hello world Chu!
            </h1>
            <button>
              Start Workout
            </button>
            <DaySheetComponent/>
          </main>
        </>
    )
}
